"""empty message

Revision ID: 2201d8ca79d5
Revises: 4671c86d0f12
Create Date: 2022-03-25 11:12:29.022753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2201d8ca79d5'
down_revision = '4671c86d0f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_urls', 'expiration_date')
    # ### end Alembic commands ###
